export const phoneDisplay = "+212 681 718 600";
export const phoneHref = "tel:+212681718600";
export const mapsUrl = "https://maps.app.goo.gl/cwN7bzsxgd7NzTCG7";

export type Locale = "fr" | "ar";

export const copy = {
  fr: {
    nav: [
      ["Accueil", "/"],
      ["Le Salon", "/salon"],
      ["Prestations", "/prestations"],
      ["Galerie", "/galerie"],
      ["Avis", "/avis"],
      ["Contact", "/contact"],
    ],
    book: "Prendre rendez-vous",
    call: "Appeler",
    callNow: "Appeler maintenant",
    direction: "Itinéraire",
    find: "Nous trouver",
    viewDirection: "Voir l’itinéraire",
    heroTitle: "Votre style. Votre élégance.",
    heroText:
      "Coiffure & barber à Nador, avec une attention particulière portée au style, aux détails et aux finitions.",
    open: "Ouvert 7j/7 • 10h00–23h00",
    detailTitle: "L’élégance dans chaque détail.",
    detailText:
      "Une adresse moderne de coiffure et barber à Nador, pensée autour du style, de la précision et de finitions impeccables.",
    servicesTitle: "Le geste juste, sans compromis.",
    servicesIntro: "Des prestations essentielles, réalisées avec soin et précision.",
    services: [
      "Coupe Homme",
      "Dégradé / Fade",
      "Barbe",
      "Coupe + Barbe",
      "Contours & Finitions",
      "Coiffure Enfant",
    ],
    experienceTitle: "Une exigence à chaque étape.",
    experience: [
      ["Précision", "Finitions propres et soignées."],
      ["Style", "Des coupes adaptées au style recherché."],
      ["Confort", "Une expérience agréable et professionnelle."],
      ["Disponibilité", "Ouvert 7j/7 de 10h à 23h."],
    ],
    galleryTitle: "L’univers Élégance.",
    galleryIntro:
      "Visuels d’ambiance — les photos réelles du salon pourront être ajoutées ici facilement.",
    reviewsTitle: "Une adresse appréciée à Nador.",
    reviewsCount: "83 avis Google",
    reviewsButton: "Voir les avis Google",
    locationTitle: "Retrouvez-nous à Nador.",
    address: "5 Rue Marrakech, Nador 62000, Maroc",
    hours: "Tous les jours • 10h00–23h00",
    getDirection: "Obtenir l’itinéraire",
    cta: "Votre prochain style commence ici.",
    salonEyebrow: "LE SALON",
    salonTitle: "Une adresse contemporaine dédiée au style masculin.",
    salonBody:
      "Coiffeure Elégance Barbier Barbershop accueille les hommes et les enfants au cœur de Nador. Chaque prestation est guidée par l’écoute, la maîtrise du geste et le soin des détails.",
    salonNote: "Qualité. Précision. Confiance.",
    galleryLabel: "VISUEL D’AMBIANCE",
    imageAlt: [
      "Fauteuil de barbier dans un intérieur sombre et élégant",
      "Outils professionnels de barbier disposés avec soin",
      "Poste de coiffure moderne avec miroirs",
    ],
    close: "Fermer",
    menu: "Ouvrir le menu",
  },
  ar: {
    nav: [
      ["الرئيسية", "/"],
      ["الصالون", "/salon"],
      ["الخدمات", "/prestations"],
      ["المعرض", "/galerie"],
      ["التقييمات", "/avis"],
      ["اتصل بنا", "/contact"],
    ],
    book: "احجز موعداً",
    call: "اتصل",
    callNow: "اتصل الآن",
    direction: "الاتجاهات",
    find: "اعثر علينا",
    viewDirection: "عرض الاتجاهات",
    heroTitle: "أسلوبك. أناقتك.",
    heroText:
      "حلاقة رجالية في الناظور بعناية خاصة بالأسلوب والتفاصيل واللمسات النهائية.",
    open: "مفتوح طوال الأسبوع • 10:00–23:00",
    detailTitle: "الأناقة في كل تفصيل.",
    detailText:
      "وجهة عصرية للحلاقة الرجالية في الناظور، ترتكز على الأسلوب والدقة وجودة اللمسات النهائية.",
    servicesTitle: "مهارة دقيقة، بلا تنازلات.",
    servicesIntro: "خدمات أساسية تُنفّذ بعناية ودقة.",
    services: [
      "قص شعر الرجال",
      "تدرج / فايد",
      "تهذيب اللحية",
      "قص الشعر + اللحية",
      "تحديد ولمسات نهائية",
      "قص شعر الأطفال",
    ],
    experienceTitle: "عناية في كل مرحلة.",
    experience: [
      ["الدقة", "لمسات نهائية نظيفة ومتقنة."],
      ["الأسلوب", "قصات تناسب الأسلوب المطلوب."],
      ["الراحة", "تجربة مريحة واحترافية."],
      ["التوفر", "مفتوح طوال الأسبوع من 10 صباحاً إلى 11 مساءً."],
    ],
    galleryTitle: "عالم الأناقة.",
    galleryIntro: "صور أجواء توضيحية — يمكن إضافة الصور الحقيقية للصالون هنا بسهولة.",
    reviewsTitle: "عنوان يحظى بالتقدير في الناظور.",
    reviewsCount: "83 تقييماً على Google",
    reviewsButton: "عرض تقييمات Google",
    locationTitle: "زورونا في الناظور.",
    address: "5 شارع مراكش، الناظور 62000، المغرب",
    hours: "كل يوم • 10:00–23:00",
    getDirection: "الحصول على الاتجاهات",
    cta: "إطلالتك القادمة تبدأ هنا.",
    salonEyebrow: "الصالون",
    salonTitle: "عنوان عصري مخصص للأناقة الرجالية.",
    salonBody:
      "يرحب صالون حلاقة الأناقة بالرجال والأطفال في قلب الناظور. تستند كل خدمة إلى حسن الاستماع وإتقان المهارة والعناية بالتفاصيل.",
    salonNote: "جودة. دقة. ثقة.",
    galleryLabel: "صورة توضيحية للأجواء",
    imageAlt: [
      "كرسي حلاقة في ديكور داكن وأنيق",
      "أدوات حلاقة احترافية مرتبة بعناية",
      "محطة حلاقة عصرية مع مرايا",
    ],
    close: "إغلاق",
    menu: "فتح القائمة",
  },
} as const;