/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as PrestationsRouteImport } from './routes/prestations'
import { Route as SalonRouteImport } from './routes/salon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestationsRoute = PrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonRoute = SalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/prestations': typeof PrestationsRoute
  '/salon': typeof SalonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/prestations': typeof PrestationsRoute
  '/salon': typeof SalonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/prestations': typeof PrestationsRoute
  '/salon': typeof SalonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avis' | '/contact' | '/galerie' | '/prestations' | '/salon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avis' | '/contact' | '/galerie' | '/prestations' | '/salon'
  id:
    | '__root__'
    | '/'
    | '/avis'
    | '/contact'
    | '/galerie'
    | '/prestations'
    | '/salon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisRoute: typeof AvisRoute
  ContactRoute: typeof ContactRoute
  GalerieRoute: typeof GalerieRoute
  PrestationsRoute: typeof PrestationsRoute
  SalonRoute: typeof SalonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestations': {
      id: '/prestations'
      path: '/prestations'
      fullPath: '/prestations'
      preLoaderRoute: typeof PrestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon': {
      id: '/salon'
      path: '/salon'
      fullPath: '/salon'
      preLoaderRoute: typeof SalonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisRoute: AvisRoute,
  ContactRoute: ContactRoute,
  GalerieRoute: GalerieRoute,
  PrestationsRoute: PrestationsRoute,
  SalonRoute: SalonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
